### ISSUE TITLE
Run-time error

### ISSUE THREAD

**Issue by pkovacs86** [microsoft/OpenXR-MixedReality#41]
I tried to run the SampleSceneWin32 sample but I got the following error:
Error [GENERAL |  | OpenXR-Loader] : RuntimeManifestFile::FindManifestFiles - failed to find active runtime file in registry
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - unknown error
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : RuntimeInterface::LoadRuntimes - failed to find a valid runtime
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed to find default runtime with RuntimeInterface::LoadRuntime()
Error [GENERAL | xrEnumerateInstanceExtensionProperties | OpenXR-Loader] : Failed querying extension properties
Exception thrown at 0x00007FFA78B9A859 in SampleSceneWin32.exe: Microsoft C++ exception: std::logic_error at memory location 0x0000008646AFCE18.
[17-13-10.748871] (t:2f00): Unhandled Exception: XrResult failure [XR_ERROR_INSTANCE_LOST]
    Origin: xrEnumerateInstanceExtensionProperties(layerName, 0, &extensionCount, nullptr)
    Source: C:\temp\OpenXR-MixedReality-master\shared\XrUtility\XrEnumerate.h:25

**Comment by yl-msft** [comment]
@pkovacs86  This error happens when you've not properly setup OpenXR runtime on your computer.  Have you tried to follow the instruct here?
https://docs.microsoft.com/en-us/windows/mixed-reality/openxr-getting-started

Especially try this app ["OpenXR Developer Tools" ](https://docs.microsoft.com/en-us/windows/mixed-reality/openxr-getting-started#getting-the-windows-mixed-reality-openxr-developer-portal)and see your runtime installation status:
![image](https://user-images.githubusercontent.com/33265158/78815810-9ecbf780-7985-11ea-89e4-2f0f06169fe4.png)

**Comment by pkovacs86** [comment]
Thank you,
[https://postimg.cc/rDkHNq8T](url)
