### ISSUE TITLE
Deploying an app to the HoloLens Emulator Error

### ISSUE THREAD

**Issue by wangdemon** [microsoft/OpenXR-MixedReality#83]
Error 1: Severity Code Description Project File Line Suppression State Error	DEP6100: The following unexpected error occurred during bootstrapping stage 'Connecting to the device 'cda37a5e-99ea-de7d-cd42-0bb8e7cd59ad'.': NullReferenceException - Object reference not set to an instance of an object. [0x80004003]	BasicXrApp_uwp

Error 2:  Severity Code Description	Project File Line Suppression State Error DEP0300: Emulator 'HoloLens 2 Emulator 10.0.20346.1002' failed to launch after 300 seconds.	BasicXrApp_uwp

**Comment by vnedelcu** [comment]
I just downloaded and installed the same version of the HoloLens 2 Emulator and I received the same error.
Anybody knows how to fix this?
Thanks

**Comment by pbarnettms** [comment]
Does your PC meet the minimum requirements for the emulator as documented at https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-hololens-emulator?  Is this a laptop or desktop? 
 Please move to 10.0.20348.1010.  If it still reproduces there, what shows in the emulator window after the timeout occurs?

**Comment by mbucchia-msft** [comment]
Hi @wangdemon and @vnedelcu, I am Matt from the OpenXR team at Microsoft.

I am trying to reproduce your error. I am using the HoloLens 2 Emulator version 10.0.20346.1002 as you posted. In the emulator, I have installed the OpenXR runtime that is available from the Microsoft Store (https://www.microsoft.com/en-us/p/openxr-for-windows-mixed-reality/9p9596djj19r). It is version 106.2105.21002. I am building the BasicXrApp_uwp project in Visual Studio 2019 with the Debug profile for x64 architecture, then I use the Remote Machine debugging feature to execute the application in the HoloLens 2 Emulator. The application is starting with no issue this way.

In order to help us resolve this issue for you, could provide the following:
1) Specific steps you are going through in order to get the error message. How do they differ from the steps I listed above?
2) Which version of the OpenXR runtime you are using? You may use the Developers Tools from the store in order to read the version: https://www.microsoft.com/en-us/p/openxr-developer-tools-for-windows-mixed-reality/9n5cvvl23qbt
3) You may also try to use the "demo scene" that is shipped with the Developer Tools (see step 2). Is the demo scene working for you?
4) Answer to @pbarnettms's question above.

Thanks for your patience, and I am looking forward to receiving more details from you.

**Comment by mbucchia-msft** [comment]
Dear customer,

Please re-open this issue if you are still having problems.

Please make sure to provide the exact instructions for reproducing the issue.

Thank you.
