### ISSUE TITLE
after update 107.2106.1002.0 runtime, scene understanding extenstion doen not work

### ISSUE THREAD

**Issue by quenakn** [microsoft/OpenXR-MixedReality#85]
sorry my english is very not good.

#define XR_MSFT_SCENE_UNDERSTANDING_PREVIEW3_EXTENSION_NAME "XR_MSFT_scene_understanding_preview3"

extension initialization failed.

so i tried like this "#define XR_MSFT_SCENE_UNDERSTANDING_PREVIEW3_EXTENSION_NAME "XR_MSFT_scene_understanding_preview"

extension initialization succeed. but scene understanding example still does not working. 

i think scene understanding api may be changed. looks like scene understanding example broken.

plz help...

**Comment by dgough** [comment]
@yl-msft has a pull request to fix this. You can checkout his branch (`yl/update_su_msft`) if you want to use it before it is merged. His pull request is #84.

The new name of the Scene Understanding extension is `XR_MSFT_scene_understanding`. It is no longer a preview extension.

We haven't merged his pull request yet because we're waiting for Khronos to publish OpenXR SDK version 1.0.17 on github. (Found here if you're curious: https://github.com/KhronosGroup/OpenXR-SDK)

**Comment by dgough** [comment]
@quenakn, pull request #84 was merged so you should be able to try this again on the `main` branch.

**Comment by yl-msft** [comment]
The latest "main" branch of this sample works with the none Preview version of the scene understanding extension: "XR_MSFT_scene_understanding"
